# Generated by Django 3.2.9 on 2021-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_host_app', '0002_file_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='count_download',
            field=models.PositiveIntegerField(default=0, verbose_name='count download'),
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='media/uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='permission_for_file',
            field=models.CharField(choices=[('PRIVAT', 'private'), ('LINK', 'link'), ('PUBLIC', 'public')], default='PRIVAT', max_length=8, verbose_name='permission for file'),
        ),
    ]
